<?php

function download($file_name) 
{     
if(is_file($file_name)) {
	// required for IE
	if(ini_get('zlib.output_compression')) { ini_set('zlib.output_compression', 'Off');	}

	// get the file mime type using the file extension
	switch(strtolower(substr(strrchr($file_name, '.'), 1))) {
	    case  '7z' : $mime = 'application/x-7z-compressed'; break; 
        case  '323' : $mime = 'text/h323'; break; 
        case  'acx' : $mime = 'application/internet-property-stream'; break; 
        case  'ai' : $mime = 'application/postscript'; break;
        case 'aif' : $mime = 'audio/x-aiff'; break;
        case'aifc' : $mime = 'audio/x-aiff'; break; 
        case  'aiff' : $mime = 'audio/x-aiff'; break;
        case 'asf' : $mime = 'video/x-ms-asf'; break; 
        case  'asr' : $mime = 'video/x-ms-asf'; break; 
        case  'asx' : $mime = 'video/x-ms-asf'; break; 
        case  'au' : $mime = 'audio/basic'; break; 
        case  'avi' : $mime = 'video/x-msvideo'; break;
        case  'axs' : $mime = 'application/olescript'; break; 
        case  'bas' : $mime = 'text/plain'; break; 
        case 'bcpio' : $mime = 'application/x-bcpio'; break;
        case  'bin' : $mime = 'application/octet-stream'; break; 
        case  'bmp' : $mime = 'image/bmp'; break;
        case  'c' : $mime = 'text/plain'; break;
        case   'cat' : $mime = 'application/vnd.ms-pkiseccat'; break;
        case  'cdf' : $mime = 'application/x-cdf'; break;
        case   'cer' : $mime = 'application/x-x509-ca-cert'; break; 
        case   'class' : $mime = 'application/octet-stream'; break; 
        case   'clp' : $mime = 'application/x-msclip'; break;
        case   'cmx' : $mime = 'image/x-cmx'; break; 
        case    'cod' : $mime = 'image/cis-cod'; break; 
        case   'cpio' : $mime = 'application/x-cpio'; break; 
        case   'crd' : $mime = 'application/x-mscardfile'; break; 
        case  'crl' : $mime = 'application/pkix-crl'; break; 
        case   'crt' : $mime = 'application/x-x509-ca-cert'; break; 
        case  'csh' : $mime = 'application/x-csh'; break; 
        case  'css' : $mime = 'text/css'; break; 
        case   'dcr' : $mime = 'application/x-director'; break;
        case   'der' : $mime = 'application/x-x509-ca-cert'; break;
        case   'dir' : $mime = 'application/x-director'; break;
        case  'dll' : $mime = 'application/x-msdownload'; break;
        case  'dms' : $mime = 'application/octet-stream'; break; 
        case   'doc' : $mime = 'application/msword'; break; 
        case   'docx' : $mime = 'application/msword'; break; 
        case  'dot' : $mime = 'application/msword'; break; 
        case  'dvi' : $mime = 'application/x-dvi'; break; 
        case  'dxr' : $mime = 'application/x-director'; break; 
        case  'eps' : $mime = 'application/postscript'; break;
        case  'etx' : $mime = 'text/x-setext'; break; 
        case 'evy' : $mime = 'application/envoy'; break; 
        case  'exe' : $mime = 'application/octet-stream'; break; 
        case  'fif' : $mime = 'application/fractals'; break;
        case 'flr' : $mime = 'x-world/x-vrml'; break; 
        case  'gif' : $mime = 'image/gif'; break; 
        case 'gtar' : $mime = 'application/x-gtar'; break;
        case 'gz' : $mime = 'application/x-gzip'; break; 
        case  'h' : $mime = 'text/plain'; break;
        case 'hdf' : $mime = 'application/x-hdf'; break; 
        case  'hlp' : $mime = 'application/winhlp'; break; 
        case  'hqx' : $mime = 'application/mac-binhex40'; break; 
        case  'hta' : $mime = 'application/hta'; break; 
        case 'htc' : $mime = 'text/x-component'; break; 
        case  'htm' : $mime = 'text/html'; break;
        case 'html' : $mime = 'text/html'; break; 
        case 'htt' : $mime = 'text/webviewhtml'; break; 
        case  'ico' : $mime = 'image/x-icon'; break;
        case  'ief' : $mime = 'image/ief'; break; 
        case 'iii' : $mime = 'application/x-iphone'; break; 
        case 'ins' : $mime = 'application/x-internet-signup'; break; 
        case  'isp' : $mime = 'application/x-internet-signup'; break; 
        case  'jfif' : $mime = 'image/pipeg'; break; 
        case  'jpe' : $mime = 'image/jpeg'; break; 
        case  'jpeg' : $mime = 'image/jpeg'; break; 
        case  'jpg' : $mime = 'image/jpeg'; break; 
        case  'js' : $mime = 'application/x-javascript'; break; 
        case 'latex' : $mime = 'application/x-latex'; break;
        case 'lha' : $mime = 'application/octet-stream'; break; 
        case 'lsf' : $mime = 'video/x-la-asf'; break; 
        case  'lsx' : $mime = 'video/x-la-asf'; break; 
        case  'lzh' : $mime = 'application/octet-stream'; break; 
        case  'm13' : $mime = 'application/x-msmediaview'; break;
        case 'm14' : $mime = 'application/x-msmediaview'; break;
        case  'm3u' : $mime = 'audio/x-mpegurl'; break; 
        case  'man' : $mime = 'application/x-troff-man'; break;
        case  'mdb' : $mime = 'application/x-msaccess'; break; 
        case  'me' : $mime = 'application/x-troff-me'; break;
        case 'mht' : $mime = 'message/rfc822'; break; 
        case  'mhtml' : $mime = 'message/rfc822'; break; 
        case 'mid' : $mime = 'audio/mid'; break; 
        case 'mny' : $mime = 'application/x-msmoney'; break;
        case 'mov' : $mime = 'video/quicktime'; break;
        case 'movie' : $mime = 'video/x-sgi-movie'; break; 
        case 'mp2' : $mime = 'video/mpeg'; break; 
        case 'mp3' : $mime = 'audio/mpeg'; break; 
        case 'mpa' : $mime = 'video/mpeg'; break; 
        case  'mpe' : $mime = 'video/mpeg'; break; 
        case 'mpeg' : $mime = 'video/mpeg'; break; 
        case  'mpg' : $mime = 'video/mpeg'; break;
        case  'mpp' : $mime = 'application/vnd.ms-project'; break;
        case 'mpv2' : $mime = 'video/mpeg'; break; 
        case  'ms' : $mime = 'application/x-troff-ms'; break;
        case 'mvb' : $mime = 'application/x-msmediaview'; break; 
        case  'nws' : $mime = 'message/rfc822'; break;
        case  'oda' : $mime = 'application/oda'; break;
        case 'p10' : $mime = 'application/pkcs10'; break;
        case 'p12' : $mime = 'application/x-pkcs12'; break; 
        case 'p7b' : $mime = 'application/x-pkcs7-certificates'; break;
        case 'p7c' : $mime = 'application/x-pkcs7-mime'; break; 
        case 'p7m' : $mime = 'application/x-pkcs7-mime'; break;
        case 'p7r' : $mime = 'application/x-pkcs7-certreqresp'; break; 
        case 'p7s' : $mime = 'application/x-pkcs7-signature'; break; 
        case  'pbm' : $mime = 'image/x-portable-bitmap'; break; 
        case 'pdf': $mime = 'application/pdf'; break;
        case 'pfx' : $mime = 'application/x-pkcs12'; break; 
        case 'pgm' : $mime = 'image/x-portable-graymap'; break; 
        case 'pko' : $mime = 'application/ynd.ms-pkipko'; break; 
        case  'pma' : $mime = 'application/x-perfmon'; break;
        case 'pmc' : $mime = 'application/x-perfmon'; break;
        case 'pml' : $mime = 'application/x-perfmon'; break; 
        case  'pmr' : $mime = 'application/x-perfmon'; break; 
        case  'pmw' : $mime = 'application/x-perfmon'; break; 
        case 'pnm' : $mime = 'image/x-portable-anymap'; break;
        case 'pot' : $mime = 'application/vnd.ms-powerpoint'; break; 
        case 'ppm' : $mime = 'image/x-portable-pixmap'; break; 
        case 'pps' : $mime = 'application/vnd.ms-powerpoint'; break;
        case 'ppt' : $mime = 'application/vnd.ms-powerpoint'; break; 
        case 'prf' : $mime = 'application/pics-rules'; break; 
        case 'ps' : $mime = 'application/postscript'; break;
        case 'pub' : $mime = 'application/x-mspublisher'; break; 
        case 'qt' : $mime = 'video/quicktime'; break;
        case 'ra' : $mime = 'audio/x-pn-realaudio'; break;
        case 'ram' : $mime = 'audio/x-pn-realaudio'; break;
        case  'ras' : $mime = 'image/x-cmu-raster'; break;
        case 'rgb' : $mime = 'image/x-rgb'; break;
        case 'rmi' : $mime = 'audio/mid'; break; 
        case 'roff' : $mime = 'application/x-troff'; break;
        case 'rtf' : $mime = 'application/rtf'; break; 
        case 'rtx' : $mime = 'text/richtext'; break; 
        case 'scd' : $mime = 'application/x-msschedule'; break; 
        case 'sct' : $mime = 'text/scriptlet'; break;
        case 'setpay' : $mime = 'application/set-payment-initiation'; break; 
        case 'setreg' : $mime = 'application/set-registration-initiation'; break; 
        case 'sh' : $mime = 'application/x-sh'; break;
        case 'shar' : $mime = 'application/x-shar'; break;
        case 'sit' : $mime = 'application/x-stuffit'; break; 
        case 'snd' : $mime = 'audio/basic'; break; 
        case  'spc' : $mime = 'application/x-pkcs7-certificates'; break;
        case 'spl' : $mime = 'application/futuresplash'; break; 
        case 'src' : $mime = 'application/x-wais-source'; break; 
        case 'sst' : $mime = 'application/vnd.ms-pkicertstore'; break;
        case 'stl' : $mime = 'application/vnd.ms-pkistl'; break;
        case 'stm' : $mime = 'text/html'; break;
        case 'svg' : $mime = 'image/svg+xml'; break; 
        case  'sv4cpio' : $mime = 'application/x-sv4cpio'; break; 
        case 'sv4crc' : $mime = 'application/x-sv4crc'; break; 
        case 't' : $mime = 'application/x-troff'; break;
        case 'tar' : $mime = 'application/x-tar'; break;
        case 'tcl' : $mime = 'application/x-tcl'; break;
        case  'tex' : $mime = 'application/x-tex'; break;
        case  'texi' : $mime = 'application/x-texinfo'; break; 
        case 'texinfo' : $mime = 'application/x-texinfo'; break; 
        case  'tgz' : $mime = 'application/x-compressed'; break; 
        case  'tif' : $mime = 'image/tiff'; break;
        case  'tiff' : $mime = 'image/tiff'; break;
        case  'tr' : $mime = 'application/x-troff'; break;
        case  'trm' : $mime = 'application/x-msterminal'; break; 
        case  'tsv' : $mime = 'text/tab-separated-values'; break;
        case 'txt' : $mime = 'text/plain'; break;
        case 'uls' : $mime = 'text/iuls'; break; 
        case 'ustar' : $mime = 'application/x-ustar'; break;
        case  'vcf' : $mime = 'text/x-vcard'; break; 
        case  'vrml' : $mime = 'x-world/x-vrml'; break; 
        case  'wav' : $mime = 'audio/x-wav'; break; 
        case 'wcm' : $mime = 'application/vnd.ms-works'; break;
        case 'wdb' : $mime = 'application/vnd.ms-works'; break;
        case  'wks' : $mime = 'application/vnd.ms-works'; break; 
        case  'wmf' : $mime = 'application/x-msmetafile'; break; 
        case  'wps' : $mime = 'application/vnd.ms-works'; break; 
        case  'wri' : $mime = 'application/x-mswrite'; break; 
        case  'wrl' : $mime = 'x-world/x-vrml'; break; 
        case   'wrz' : $mime = 'x-world/x-vrml'; break; 
        case  'xaf' : $mime = 'x-world/x-vrml'; break; 
        case 'xbm' : $mime = 'image/x-xbitmap'; break; 
        case    'xla' : $mime = 'application/vnd.ms-excel'; break;
        case  'xlc' : $mime = 'application/vnd.ms-excel'; break; 
        case  'xlm' : $mime = 'application/vnd.ms-excel'; break; 
        case  'xls' : $mime = 'application/vnd.ms-excel'; break; 
        case  'xlsx' : $mime = 'application/vnd.ms-excel'; break; 
        case   'xlt' : $mime = 'application/vnd.ms-excel'; break; 
        case  'xlw' : $mime = 'application/vnd.ms-excel'; break; 
        case  'xof' : $mime = 'x-world/x-vrml'; break; 
        case  'xpm' : $mime = 'image/x-xpixmap'; break; 
        case  'xwd' : $mime = 'image/x-xwindowdump'; break;
        case  'z' : $mime = 'application/x-compress'; break; 
        case  'rar' : $mime = 'application/x-rar-compressed'; break;
        case  'zip' : $mime = 'application/zip'; break;
        default: $mime = 'application/force-download';
                          }
                          
            header('Pragma: public');   
            header('Expires: 0');       //0 is no cache
            header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
            header('Last-Modified: '.gmdate ('D, d M Y H:i:s', filemtime ($file_name)).' GMT');
            header('Cache-Control: private',false);
            header('Content-Type: '.$mime);
            header('Content-Disposition: attachment; filename="'.basename($file_name).'"');
            header('Content-Transfer-Encoding: binary');
            header('Content-Length: '.filesize($file_name));    // provide the full file size
            header('Connection: close');
            readfile($file_name);       //Standard push the file to browser
            exit();
        }
        }
        ?>
